local m = require "part1"
local Point3D = require("utils.point3d")
pcall(function() require("lldebugger").start() end)
describe("solutions", function()
    it("test input", function()
        assert.are.equal(40, m.solution("./inputs/test.txt", 10))
    end)
    it("Euclidean distance", function()
        local point = Point3D(1, 2, 3)
        assert.are.equal(0, m.euclidean_distance(point, point))
    end)
    it("input", function()
        assert.are.equal(0, m.solution("./inputs/input.txt", 1000))
    end)
end)
