local m = require "part2"
pcall(function() require("lldebugger").start() end)
describe("solutions", function()
    it("test input", function()
        assert.are.equal(24, m.solution("./inputs/test.txt"))
    end)
    it("input", function()
        assert.are.equal(1574684850, m.solution("./inputs/input.txt"))
    end)
end)
