local m = require "part1"
pcall(function() require("lldebugger").start() end)
describe("solutions", function()
    it("calculates rectangle area of two opposite points", function()
        assert.are.equal(24, m.get_area({ x = 2, y = 5 }, { x = 9, y = 7 }))
        assert.are.equal(35, m.get_area({ x = 7, y = 1 }, { x = 11, y = 7 }))
        assert.are.equal(6, m.get_area({ x = 7, y = 3 }, { x = 2, y = 3 }))
        assert.are.equal(50, m.get_area({ x = 2, y = 5 }, { x = 11, y = 1 }))
    end)
    it("test input", function()
        assert.are.equal(50, m.solution("./inputs/test.txt"))
    end)
    it("input", function()
        assert.are.equal(0, m.solution("./inputs/input.txt"))
    end)
end)
