local m = require "part1"
pcall(function() require("lldebugger").start() end)
describe("solutions", function()
    it("load_data parses test.txt correctly", function()
        local ranges, ingredient_ids = m.load_data("./inputs/test.txt")
        assert.are.equal(4, #ranges)
        assert.are.equal(3, ranges[1].min)
        assert.are.equal(5, ranges[1].max)
        assert.are.equal(10, ranges[2].min)
        assert.are.equal(14, ranges[2].max)
        assert.are.equal(16, ranges[3].min)
        assert.are.equal(20, ranges[3].max)
        assert.are.equal(12, ranges[4].min)
        assert.are.equal(18, ranges[4].max)
        assert.are.equal(6, #ingredient_ids)
        assert.are.equal(1, ingredient_ids[1])
        assert.are.equal(5, ingredient_ids[2])
        assert.are.equal(8, ingredient_ids[3])
        assert.are.equal(11, ingredient_ids[4])
        assert.are.equal(17, ingredient_ids[5])
        assert.are.equal(32, ingredient_ids[6])
    end)
    it("marks as fresh", function()
        local ranges = m.load_data("./inputs/test.txt")
        local is_fresh = true
        assert.are.equal(not is_fresh, m.check_freshness(1, ranges))
        assert.are.equal(is_fresh, m.check_freshness(5, ranges))
        assert.are.equal(not is_fresh, m.check_freshness(8, ranges))
        assert.are.equal(is_fresh, m.check_freshness(11, ranges))
        assert.are.equal(is_fresh, m.check_freshness(17, ranges))
        assert.are.equal(not is_fresh, m.check_freshness(32, ranges))
    end)
    it("test input", function()
        assert.are.equal(3, m.solution("./inputs/test.txt"))
    end)
    it("input", function()
        assert.are.equal(789, m.solution("./inputs/input.txt"))
    end)
end)
