local m = require "part2"
pcall(function() require("lldebugger").start() end)
describe("solutions", function()
    it("test input", function()
        assert.are.equal(14, m.solution("./inputs/test.txt"))
    end)
    it("input", function()
        assert.are.equal(343329651880509, m.solution("./inputs/input.txt"))
    end)
end)
