local m = require "part2"
pcall(function() require("lldebugger").start() end)
describe("solutions", function()
    it("test input", function()
        assert.are.equal(2, m.solution("./inputs/test-part2.txt"))
    end)
    it("input", function()
        -- assert.are.equal(0, m.solution("./inputs/input.txt"))
    end)
end)
