local m = require "part2"
local file_utils = require "utils.file"
pcall(function() require("lldebugger").start() end)
describe("solutions", function()
    it("processes grid input", function()
        local test_input = file_utils.read_file("./inputs/test.txt")
        m.create_grid("./inputs/test.txt")
        assert.are.equal("\n" .. test_input, "\n" .. m.grid:to_s())
    end)
    it("is_coordinate_allowed", function()
        m.create_grid("./inputs/test.txt")
        assert.are.equal(true, m.is_coordinate_allowed(3, 1))
        assert.are.equal(true, m.is_coordinate_allowed(4, 1))
        assert.are.equal(true, m.is_coordinate_allowed(1, 2))
        assert.are.equal(false, m.is_coordinate_allowed(2, 2))
    end)
    it("test input", function()
        assert.are.equal(43, m.solution("./inputs/test.txt"))
    end)

    it("input", function()
        assert.are.equal(8722, m.solution("./inputs/input.txt"))
    end)
end)
